"""sailsim_physics.py — batched numpy port of src/physics.js + collision.js.

Every function takes arrays of shape (N,) (a batch of N boats) and returns the
same.  State layout matches the JS: s = [xE, yN, psi, u, v, r, delta, n], here
an array of shape (8, N).  Conventions are identical to the JS (body x forward,
y starboard; heading clockwise from north; alpha = delta + atan2(v, u)).

The parameter block is a copy of JEANNEAU_36; test_port.py checks a trajectory
against a fixture generated by the JS, so drift between the two shows up.
"""
import numpy as np

RHO_W, RHO_A = 1025.0, 1.225
DEG, KN = np.pi / 180, 0.514444

P = dict(
    LOA=10.94, LWL=9.84, beam=3.59, mass=6200.0, kzz=0.25 * 10.94,
    addedMass=dict(ax=0.05, ay=0.55, az=0.35, munk=1.0),
    hull=dict(T0=0.60, kQuad=110.0, kLin=60.0, cdCross=1.0, nStrips=24),
    keel=dict(area=2.0, ar=2.2, x=-0.3, cd0=0.008, e=0.8, alphaStall=12 * DEG, cn=1.5),
    rudder=dict(area=0.75, ar=3.0, x=-4.6, cd0=0.010, e=0.8, alphaStall=15 * DEG, cn=1.5,
                deltaMax=35 * DEG, span=1.5),
    wheel=dict(lockToLockTurns=2.0, rateMin=90 * DEG, rateMax=360 * DEG, rampTime=1.0),
    prop=dict(D=0.42, Kt0=0.26, J0=0.85, astern=0.85, gearAhead=2.21, gearAstern=3.06,
              x=-4.0, wake=0.05, slipFrac=0.50, kR=0.5, tau=0.8),
    engine=dict(ahead=[0, 800, 1000, 1500, 2000, 2500], astern=[0, 800, 1000, 1500, 2000]),
    windage=dict(areaFrontal=6.0, areaLateral=18.0, cx=0.7, cy=0.9, xCE=0.5),
    outline=np.array([[5.47, 0], [4.6, 0.75], [3.2, 1.40], [1.2, 1.78], [-1.4, 1.76], [-3.4, 1.55],
                      [-4.9, 1.20], [-5.47, 0.95], [-5.47, -0.95], [-4.9, -1.20], [-3.4, -1.55],
                      [-1.4, -1.76], [1.2, -1.78], [3.2, -1.40], [4.6, -0.75]]),
)
CONTACT = dict(k=25000.0, c=6000.0, mu=0.4, sampleSpacing=0.3)


def derived(P=P):
    m, Izz = P['mass'], P['mass'] * P['kzz'] ** 2
    A = P['addedMass']
    ll = P['wheel']['lockToLockTurns'] * 2 * np.pi
    return dict(m=m, Izz=Izz, mx=m * (1 + A['ax']), my=m * (1 + A['ay']), Iz=Izz * (1 + A['az']),
                rudderRateMin=P['wheel']['rateMin'] * 2 * P['rudder']['deltaMax'] / ll,
                rudderRateMax=P['wheel']['rateMax'] * 2 * P['rudder']['deltaMax'] / ll)


# ------------------------------------------------------------------ foils
def foil_coeffs(alpha, f):
    a = alpha - np.pi * np.round(alpha / np.pi)
    ar = f['ar']
    cl_alpha = 2 * np.pi * ar / (2 + np.sqrt(ar * ar + 4))
    cl_lin = cl_alpha * a
    cd_lin = f['cd0'] + cl_lin ** 2 / (np.pi * f['e'] * ar)
    sa, ca = np.sin(a), np.cos(a)
    cl_fp, cd_fp = f['cn'] * sa * ca, f['cn'] * sa * sa
    w = np.clip((np.abs(a) - f['alphaStall']) / (0.5 * f['alphaStall']), 0, 1)
    w = w * w * (3 - 2 * w)
    return (1 - w) * cl_lin + w * cl_fp, (1 - w) * cd_lin + w * cd_fp


def foil_force(uIn, vIn, delta, f, area):
    V2 = uIn * uIn + vIn * vIn
    V = np.sqrt(np.maximum(V2, 1e-12))
    alpha = delta + np.arctan2(vIn, uIn)
    cl, cd = foil_coeffs(alpha, f)
    q = 0.5 * RHO_W * area * V2
    dx, dy = -uIn / V, -vIn / V
    nx, ny = -dy, dx
    X, Y = q * (cd * dx + cl * nx), q * (cd * dy + cl * ny)
    ok = V2 >= 1e-6
    return np.where(ok, X, 0.0), np.where(ok, Y, 0.0)


# ------------------------------------------------------------------ hull, keel
def hull_forces(u, v, r, P=P):
    H, L, Ns = P['hull'], P['LWL'], P['hull']['nStrips']
    dx = L / Ns
    x = -L / 2 + (np.arange(Ns) + 0.5) * dx                    # (Ns,)
    T = H['T0'] * (1 - (2 * x / L) ** 2)
    vl = v[None, :] + x[:, None] * r[None, :]                   # (Ns, N)
    dY = -0.5 * RHO_W * H['cdCross'] * T[:, None] * np.abs(vl) * vl * dx
    X = -(H['kQuad'] * u * np.abs(u) + H['kLin'] * u)
    return X, dY.sum(0), (x[:, None] * dY).sum(0)


def keel_forces(u, v, r, P=P):
    k = P['keel']
    X, Y = foil_force(u, v + k['x'] * r, 0.0, k, k['area'])
    return X, Y, k['x'] * Y


# ------------------------------------------------------------------ propeller, rudder
def prop_thrust(u, n, P=P):
    p = P['prop']
    uA = u * (1 - p['wake'])
    sn = np.sign(n)
    an = np.maximum(np.abs(n), 1e-9)
    Ja = sn * uA / (an * p['D'])
    Kt = np.clip(p['Kt0'] * (1 - Ja / p['J0']), -0.5 * p['Kt0'], 1.5 * p['Kt0'])
    T = sn * RHO_W * n * n * p['D'] ** 4 * Kt * np.where(n < 0, p['astern'], 1.0)
    return np.where(np.abs(n) < 1e-6, 0.0, T), uA


def rudder_forces(u, v, r, delta, T, P=P):
    R, p = P['rudder'], P['prop']
    Ap = np.pi * p['D'] ** 2 / 4
    vIn = v + R['x'] * r
    uA = u * (1 - p['wake'])
    uW = np.sqrt(uA * uA + 2 * np.maximum(T, 0) / (RHO_W * Ap))
    uSlip = np.where(T > 0, uA + p['kR'] * (uW - uA), u)
    Xs, Ys = foil_force(uSlip, vIn, delta, R, R['area'] * p['slipFrac'])
    Xf, Yf = foil_force(u, vIn, delta, R, R['area'] * (1 - p['slipFrac']))
    Y = Ys + Yf
    return Xs + Xf, Y, R['x'] * Y


# ------------------------------------------------------------------ windage
def wind_forces(S, wE, wN, P=P):
    psi, u, v = S[2], S[3], S[4]
    W = P['windage']
    sp, cp = np.sin(psi), np.cos(psi)
    vE, vN = u * sp + v * cp, u * cp - v * sp
    aE, aN = wE - vE, wN - vN
    wx, wy = aE * sp + aN * cp, aE * cp - aN * sp
    Wm = np.hypot(wx, wy)
    X = 0.5 * RHO_A * W['cx'] * W['areaFrontal'] * Wm * wx
    Y = 0.5 * RHO_A * W['cy'] * W['areaLateral'] * Wm * wy
    return X, Y, W['xCE'] * Y


# ------------------------------------------------------------------ controls
def rpm_setpoint(idx, P=P):
    ah, at = np.array(P['engine']['ahead']), np.array(P['engine']['astern'])
    idx = np.asarray(idx, dtype=int)
    pos = ah[np.clip(idx, 0, len(ah) - 1)]
    neg = -at[np.clip(-idx, 0, len(at) - 1)]
    return np.where(idx >= 0, pos, neg).astype(float)


def engine_to_shaft(rpm, P=P):
    p = P['prop']
    return rpm / 60 / np.where(rpm < 0, p['gearAstern'], p['gearAhead'])


def shaft_to_engine(n, P=P):
    p = P['prop']
    return n * 60 * np.where(n < 0, p['gearAstern'], p['gearAhead'])


# ------------------------------------------------------------------ contact
def sample_outline(outline, spacing=CONTACT['sampleSpacing']):
    pts = []
    for i in range(len(outline)):
        x0, y0 = outline[i]; x1, y1 = outline[(i + 1) % len(outline)]
        L = np.hypot(x1 - x0, y1 - y0); n = max(1, int(np.ceil(L / spacing)))
        for k in range(n):
            pts.append([x0 + (x1 - x0) * k / n, y0 + (y1 - y0) * k / n])
    return np.array(pts)


def point_in_polygon(px, py, poly):
    """px, py arrays of any shape; poly (V,2).  Ray-casting parity, as in the JS."""
    inside = np.zeros(px.shape, dtype=bool)
    V = len(poly)
    for i in range(V):
        xi, yi = poly[i]; xj, yj = poly[i - 1]
        cond = ((yi > py) != (yj > py)) & (px < (xj - xi) * (py - yi) / ((yj - yi) if yj != yi else 1e-12) + xi)
        inside ^= cond
    return inside


def nearest_edge(px, py, poly):
    """Returns d, nx, ny: distance to the polygon boundary and unit vector from p toward it."""
    best_d = np.full(px.shape, np.inf); bnx = np.zeros(px.shape); bny = np.zeros(px.shape)
    V = len(poly)
    for i in range(V):
        ax, ay = poly[i - 1]; bx, by = poly[i]
        abx, aby = bx - ax, by - ay; L2 = abx * abx + aby * aby or 1e-12
        t = np.clip(((px - ax) * abx + (py - ay) * aby) / L2, 0, 1)
        qx, qy = ax + t * abx, ay + t * aby
        d = np.hypot(qx - px, qy - py)
        m = d < best_d
        best_d = np.where(m, d, best_d)
        bnx = np.where(m, (qx - px) / np.maximum(d, 1e-9), bnx)
        bny = np.where(m, (qy - py) / np.maximum(d, 1e-9), bny)
    return best_d, bnx, bny


def contact_forces(S, hull_pts, docks, water, C=CONTACT):
    """Body-frame X, Y, N (N,) plus integrated penetration depth (N,) for penalties."""
    xE, yN, psi, u, v, r = S[0], S[1], S[2], S[3], S[4], S[5]
    sp, cp = np.sin(psi), np.cos(psi)
    bx, by = hull_pts[:, 0][:, None], hull_pts[:, 1][:, None]        # (M,1)
    pE = xE[None] + bx * sp[None] + by * cp[None]                     # (M,N)
    pN = yN[None] + bx * cp[None] - by * sp[None]
    vbx, vby = u[None] - r[None] * by, v[None] + r[None] * bx
    vE, vN = vbx * sp[None] + vby * cp[None], vbx * cp[None] - vby * sp[None]
    X = np.zeros_like(xE); Y = np.zeros_like(xE); Nz = np.zeros_like(xE); pen = np.zeros_like(xE)

    def apply(mask, d, nx, ny):
        nonlocal X, Y, Nz, pen
        vn = vE * nx + vN * ny
        Fn = np.where(mask, np.maximum(0, C['k'] * d - C['c'] * vn), 0.0)
        tx, ty = -ny, nx
        vt = vE * tx + vN * ty
        Ft = -np.sign(vt) * np.minimum(C['mu'] * Fn, C['c'] * np.abs(vt))
        FE, FN = Fn * nx + Ft * tx, Fn * ny + Ft * ty
        Fx, Fy = FE * sp[None] + FN * cp[None], FE * cp[None] - FN * sp[None]
        X = X + Fx.sum(0); Y = Y + Fy.sum(0); Nz = Nz + (bx * Fy - by * Fx).sum(0)
        pen = pen + np.where(mask, d, 0.0).sum(0)

    for poly in docks:
        # bounding-box precheck: skip polygons no hull point can be inside
        if not ((pE >= poly[:, 0].min()) & (pE <= poly[:, 0].max()) & (pN >= poly[:, 1].min()) & (pN <= poly[:, 1].max())).any():
            continue
        inside = point_in_polygon(pE, pN, poly)
        if not inside.any():
            continue
        d, nx, ny = nearest_edge(pE, pN, poly)
        apply(inside, d, nx, ny)
    if len(water):
        in_any = np.zeros(pE.shape, dtype=bool)
        for poly in water:
            in_any |= point_in_polygon(pE, pN, poly)
        out = ~in_any
        if out.any():
            bd = np.full(pE.shape, np.inf); bnx = np.zeros(pE.shape); bny = np.zeros(pE.shape)
            for poly in water:
                d, nx, ny = nearest_edge(pE, pN, poly)
                m = d < bd
                bd = np.where(m, d, bd); bnx = np.where(m, nx, bnx); bny = np.where(m, ny, bny)
            apply(out, bd, bnx, bny)
    return X, Y, Nz, pen


# ------------------------------------------------------------------ dynamics
def derivative(S, inp, P=P, extra=None):
    """inp: dict with rudder_rate (N,) [rad/s, signed], rpm_set (N,), wE, wN (N,) or scalars."""
    D = derived(P)
    psi, u, v, r, delta, n = S[2], S[3], S[4], S[5], S[6], S[7]
    Xh, Yh, Nh = hull_forces(u, v, r, P)
    Xk, Yk, Nk = keel_forces(u, v, r, P)
    T, _ = prop_thrust(u, n, P)
    Xr, Yr, Nr = rudder_forces(u, v, r, delta, T, P)
    Xw, Yw, Nw = wind_forces(S, inp['wE'], inp['wN'], P)
    Xe = Ye = Ne = 0.0
    if extra is not None:
        Xe, Ye, Ne = extra(S)
    X = Xh + Xk + T + Xr + Xw + Xe
    Y = Yh + Yk + Yr + Yw + Ye
    Nz = Nh + Nk + Nr + Nw + Ne
    du = (X + D['my'] * v * r) / D['mx']
    dv = (Y - D['mx'] * u * r) / D['my']
    dr = (Nz - P['addedMass']['munk'] * (D['my'] - D['mx']) * u * v) / D['Iz']
    sp, cp = np.sin(psi), np.cos(psi)
    dmax = P['rudder']['deltaMax']
    dd = inp['rudder_rate']
    dd = np.where((delta >= dmax) & (dd > 0), 0.0, dd)
    dd = np.where((delta <= -dmax) & (dd < 0), 0.0, dd)
    nSet = engine_to_shaft(inp['rpm_set'], P)
    dn = (nSet - n) / P['prop']['tau']
    return np.stack([u * sp + v * cp, u * cp - v * sp, r, du, dv, dr, dd, dn])


def rk4_step(S, inp, h, P=P, extra=None):
    f = lambda s: derivative(s, inp, P, extra)
    k1 = f(S); k2 = f(S + h / 2 * k1); k3 = f(S + h / 2 * k2); k4 = f(S + h * k3)
    out = S + h / 6 * (k1 + 2 * k2 + 2 * k3 + k4)
    dm = P['rudder']['deltaMax']
    out[6] = np.clip(out[6], -dm, dm)
    out[2] = (out[2] + np.pi) % (2 * np.pi) - np.pi
    return out


def initial_state(N, xE=0.0, yN=0.0, psi_deg=0.0):
    S = np.zeros((8, N))
    S[0] = xE; S[1] = yN; S[2] = psi_deg * DEG
    return S
